[[mods]]
modId = "notenoughpalette"
version = "${version}"
displayName = "NotEnoughPalette"
description = "Optimize Minecraft's PalettedContainer."
license = "MIT"
logoFile = "assets/notenoughpalette/icon.png"

[[mixins]]
config = "notenoughpalette.mixins.json"
